# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.proto.v1 import auth_pb2 as api_dot_proto_dot_v1_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/proto/v1/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/v1.AuthService/Register',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/v1.AuthService/Login',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/v1.AuthService/Logout',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/v1.AuthService/RefreshToken',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.TokenPair.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/v1.AuthService/ForgotPassword',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.ForgotPasswordRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/v1.AuthService/ResetPassword',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.SendVerificationEmail = channel.unary_unary(
                '/v1.AuthService/SendVerificationEmail',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.VerifyEmail = channel.unary_unary(
                '/v1.AuthService/VerifyEmail',
                request_serializer=api_dot_proto_dot_v1_dot_auth__pb2.VerifyEmailRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Register a new user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout (Invalidate refresh token)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Refresh Tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Forgot Password (Send email)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Reset Password (Use token from email)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVerificationEmail(self, request, context):
        """Send Verification Email (Authenticated user)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Verify Email (Use token from email)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.TokenPair.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.ForgotPasswordRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.ResetPasswordRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.SerializeToString,
            ),
            'SendVerificationEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVerificationEmail,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.Empty.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=api_dot_proto_dot_v1_dot_auth__pb2.VerifyEmailRequest.FromString,
                    response_serializer=api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/Register',
            api_dot_proto_dot_v1_dot_auth__pb2.RegisterRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/Login',
            api_dot_proto_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/Logout',
            api_dot_proto_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/RefreshToken',
            api_dot_proto_dot_v1_dot_auth__pb2.RefreshTokenRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.TokenPair.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/ForgotPassword',
            api_dot_proto_dot_v1_dot_auth__pb2.ForgotPasswordRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/ResetPassword',
            api_dot_proto_dot_v1_dot_auth__pb2.ResetPasswordRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVerificationEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/SendVerificationEmail',
            api_dot_proto_dot_v1_dot_auth__pb2.Empty.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AuthService/VerifyEmail',
            api_dot_proto_dot_v1_dot_auth__pb2.VerifyEmailRequest.SerializeToString,
            api_dot_proto_dot_v1_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
