# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/v1/health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/proto/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/proto/v1/health.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2c\n\rHealthService\x12R\n\x0bHealthCheck\x12\x16.v1.HealthCheckRequest\x1a\x17.v1.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/healthB\'Z%starter-kit-grpc-golang/api/gen/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%starter-kit-grpc-golang/api/gen/v1;v1'
  _globals['_HEALTHSERVICE'].methods_by_name['HealthCheck']._loaded_options = None
  _globals['_HEALTHSERVICE'].methods_by_name['HealthCheck']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/health'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=63
  _globals['_HEALTHCHECKREQUEST']._serialized_end=83
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=85
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=139
  _globals['_HEALTHSERVICE']._serialized_start=141
  _globals['_HEALTHSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
